### PR TITLE
repull of #450.

### PR DESCRIPTION
**Pull request by Amachik**
problem with merging via desynced files.

### CODE REVIEW

**Comment by Amachik** [comment]
it should be all fixed now. i hope.

**Review by Amachik — COMMENTED** [review]
looks ok to me.

**Comment by TheMoonThatRises** [comment]
> it should be all fixed now. i hope.

Unfortunately, there is one in StoreAppView that still isn't fixed.

**Comment by Amachik** [comment]
> > it should be all fixed now. i hope.
> 
> Unfortunately, there is one in StoreAppView that still isn't fixed.

huh? what is it this time? im not discarding any changes

**Review by Amachik — COMMENTED** [review]
im done with it >}

**Comment by amirsaam** [comment]
Can we also prohibit users from installing it?
Malicious apps are different with regular prohibited, those are ban risks and users can bypass it with no real damage, but malicious are red flag, users should not be able to install it through PlayCover.

**Comment by Amachik** [comment]
> Can we also prohibit users from installing it?
> Malicious apps are different with regular prohibited, those are ban risks and users can bypass it with no real damage, but malicious are red flag, users should not be able to install it through PlayCover.

i can def. add this feature in addition to this. i will add this later on. this pr is now complete.

**Review by Depal1 — APPROVED** [review]

**Pull request merged**
