### PR TITLE
Translation section in README

### PR DESCRIPTION
**Pull request by zanderp25**
I looked into the api and it seemed like weblate would not let it retrieve the data... either that or they changed the Weblate API and the other site hasnt updated yet.

Also, I added a translations section, which might seem more fitting, but I'm not sure if i want to keep that wording.

### CODE REVIEW

**Comment by IsaacMarovitz** [comment]
The translation badge works some of the time (like right now)

**Comment by IsaacMarovitz** [comment]
image
I'm guessing it's an issue on weblate's side

**Comment by zanderp25** [comment]
Oh, well that's weird. It's still not working for me.

Screen Shot 2022-08-22 at 11 25 34

Should we still keep the translation section though?

**Review by zanderp25 — COMMENTED** [review]
wait why doesn't this work

**Comment by Candygoblen123** [comment]
seems to work for me

**Comment by zanderp25** [comment]
Aight im gonna close this

**Pull request closed without merging**
