### PR TITLE
Fix automatic screen size detection

### PR DESCRIPTION
**Pull request by zanderp25**
Previous builds of PlayCover had an issue where the automatic screen size option would not use the correct aspect ratio (and apparently eventually became square?)

This fix sets the window size to the size of the full screen. If a notch is detected, it forces the aspect ratio to 16:10, which is the correct ratio of the screen size without the notch.

### CODE REVIEW

**Comment by ZhichGaming** [comment]
Did you set display mode Auto as the default behavior?

**Comment by zanderp25** [comment]
> Did you set display mode Auto as the default behavior?

I didn't change any default behavior

**Comment by ZhichGaming** [comment]
I think it should default as auto since that is the ideal settings that will probably work for most users.

**Comment by zanderp25** [comment]
one sec lemme fix the issues

**Comment by zanderp25** [comment]
Alright the issues should be fixed now and i set the default

**Review by Depal1 — APPROVED** [review]

**Pull request merged**
