### PR TITLE
Release: 1.1.0

### PR DESCRIPTION
**Pull request by lixin9311**
## Changes:
- Updated localizations and a new localization system (some localizations may be broken)
- Sparkle updater
- High resolutions (1080p, 1440p and 4K with a 16:9 aspect ratio)
- M2 MacBook Air notch fix
- Starting to deal with keymapping jankness
- Genshin account switcher
- Refreshed UI on launcher and app settings
- Menu bar rework with shortcuts
- Reworked main app grid
- Updated help tab
- Disable display sleep mode for apps
- Added an iPad model identifier picker for 1st, 3rd and 5th generation 12,9” iPad Pros.

## Fixes:
- Fixed Swift deprecations
- Fixed an issue where PlayCover would crash when started on some audio bit rates
- Fixed an issue where the reset app settings button would not reset app settings.
- Removed unused assets and code
- Removed old and deprecated objective C code
- Removed tabs

TODOs:
- [ ] Appcast update in CI
- [ ] Dynamic configuration for JB Bypass

### CODE REVIEW

**Comment by IsaacMarovitz** [comment]
Release Notes:
---

WHOOOOO get hyped y'all its a big 'un!

Features:
+ Added Adaptive Display (10800, 1440p, and 4K!)
+ Added Sparkle updater
+ Added Genshin Impact account switcher
+ Added new Documentation (https://docs.playcover.io/)
+ Added M2 MacBook Air notch support
+ Added nightly update branch
+ Added tabbed settings view
+ Refreshed UI
    + 'Show app links' moved to View Menu
    + 'Website', 'GitHub', 'Discord', and 'Documentation' added to Help Menu
    + A bunch of other tweaks
+ New localization system (will require new translations but should keep everything consistent between languages)

Fixes:
+ Fixed an issue where main app grid had horrible performance
+ Fixed an issue where PlayCover would mess with audio settings
+ Fixed a crash that would sometimes occur when opening the app
+ Disabled tabs
+ Removed a bunch of unused assets and code
+ A bunch of other technical stuff

**Comment by Candygoblen123** [comment]
Some things that would be nice to merge before releasing 1.1.0:

#137 Chore: add sparkle to CI
#133 fix infinite loop after enabling playsign

**Comment by JoseMoreville** [comment]
Wow, almost there!

**Comment by lixin9311** [comment]
change base to release 1.1.0

**Pull request closed without merging**
