### PR TITLE
[Localization] NEW: Persian/Farsi (fa_IR)

### PR DESCRIPTION
**Pull request by amirsaam**
I think it would need some UI tweaks because of Persian/Farsi being a RTL language.

### CODE REVIEW

**Comment by IsaacMarovitz** [comment]
RTL languages will be supported in >2.0.0 but are currently untested in 1.1.1

**Comment by amirsaam** [comment]
Does it need further works from my side or it's ok for now until later?

**Comment by IsaacMarovitz** [comment]
I'm testing in 1.1.1 now, will upload screenshots in a sec

**Comment by IsaacMarovitz** [comment]
Screenshot 2022-08-20 at 19 02 53
Screenshot 2022-08-20 at 19 03 11
Screenshot 2022-08-20 at 19 03 23
Looks mostly good. Let me know if you see any issues

**Comment by IsaacMarovitz** [comment]
Screenshot 2022-08-20 at 19 04 33

**Comment by amirsaam** [comment]
It's looking good to me.
Only on "Experiencing an issue?" page looks like the texts are not wrapped.
On the step 7, you can tell the texts are not showing and instead go to next line they became "..."

And I need to change one translation.

**Comment by amirsaam** [comment]
And I didn't know PlayCover is on Hosted Weblate ready for translate 💀

**Review by Depal1 — APPROVED** [review]

**Comment by Candygoblen123** [comment]
> And I didn't know PlayCover is on Hosted Weblate ready for translate 💀

yeah it was just create, there was no way for you to have known.

**Pull request merged**
