### PR TITLE
Fix keymappings

### PR DESCRIPTION
**Pull request by TheMoonThatRises**
Fixes bug where keymappings are exported to blank slates. Also fixes the bug where draggableButtonModels are not able to be exported.

### CODE REVIEW

**Comment by IsaacMarovitz** [comment]
Could you provide some examples of times where the current exporter fasley exports blank states?

**Comment by TheMoonThatRises** [comment]
I have tested this mainly on Genshin, and it is when I create a keymap within it and try to export it. In the keymapping directory it shows the correct plist, but when it is exported, it becomes blank (in the sense that there are no keys on it).

**Comment by ZhichGaming** [comment]
Do you mean for the new button only? The draggable button one?

**Comment by TheMoonThatRises** [comment]
None of the buttons are saved when they are exported.

**Comment by TheMoonThatRises** [comment]
Also, the draggable button option doesn't even have a key in the plist.

**Comment by ZhichGaming** [comment]
I can reproduce this issue on the lastest nightly.

**Comment by IsaacMarovitz** [comment]
I wasn't aware of the CGFloat/Float mismatch between PlayTools and PlayCover code. These changes are necessary.

**Review by IsaacMarovitz — APPROVED** [review]

**Review by Depal1 — APPROVED** [review]

**Pull request merged**
