### PR TITLE
UI Updates

### PR DESCRIPTION
**Pull request by lockieluke**
Updated title bar to Big Sur's style and App Settings buttons

image

image

### CODE REVIEW

**Comment by ohaiibuzzle** [comment]
I am not too sure if this is very necessary

Regarding the title bar, the HIG says this: "Display a title unless the window’s content provides enough context to make one unnecessary. For document windows, the title is the name of the document or Untitled (for new documents). For app windows, the title is the name of the app", which I think PlayCover qualifies for

As for the buttons, maybe?
I think we should have more opinions on this

**Comment by lockieluke** [comment]
Should probably move the search bar and the buttons to the title bar

**Comment by zanderp25** [comment]
I don't like how the done button is a link, either.

**Comment by ohaiibuzzle** [comment]
> Should probably move the search bar and the buttons to the title bar

We may end up making the buttons menu items at some point as they are very much optional, and may end up rarely used (the show app links option already is in the latest build).
That leaves the search bar, which, probably better off just spanning the entire window than constraint to the top right.

**Comment by lockieluke** [comment]
that's what I meant we should put the search field into the NSToolbae

**Comment by Depal1** [comment]
As stated above, the titlebar should not be included, and the 'Done' button would be better off bordered and with accent color to follow macOS' design.

**Comment by lockieluke** [comment]
Ok got it I'll try to implement those changes

**Comment by Depal1** [comment]
Superseded by https://github.com/PlayCover/PlayCover/pull/135.

**Pull request closed without merging**
