### PR TITLE
Updated Localizable.strings (EN)

### PR DESCRIPTION
**Pull request by AarnavSin**
Fixed a lot of grammatical, punctuation and spelling errors. Rewrote certain lines to fit the purpose better.

### CODE REVIEW

**Comment by AarnavSin** [comment]
> Fixed a lot of grammatical, punctuation and spelling errors. Rewrote certain lines to fit the purpose better.

Resolving a problem with how the file has been edited, don't merge.

**Comment by AarnavSin** [comment]
> > Fixed a lot of grammatical, punctuation and spelling errors. Rewrote certain lines to fit the purpose better.
> 
> Resolving a problem with how the file has been edited, don't merge.

Said changes have been completed, as far as I have seen it is ready to go. Waiting for a review.

**Comment by AarnavSin** [comment]
> Fixed yet another problem lol. Build finally succeded.

Build confirmed to be working, changes are visible.

**Comment by Depal1** [comment]
Conflicts with #86.

**Pull request closed without merging**
