### PR TITLE
UI Tweaks + Translations

### PR DESCRIPTION
**Pull request by ohaiibuzzle**
Tweaked the PlayCover top bar: 
- adding ample paddings to the elements
- centering the Sideloadly button

Translations:
- tweaking elements to use NSLocalizedString
- added the rest of the strings into the English localizable

### CODE REVIEW

**Review by lixin9311 — APPROVED** [review]
That is great!! But some translations are missing for now.

**Comment by ohaiibuzzle** [comment]
Yes. I'm working on my translations (Vietnamese) while trying to contact the other contributors that made the other translations.

**Comment by ZhichGaming** [comment]
Can at least the padding of the button be merged? We can still keep this open to wait for the translations.

**Comment by lixin9311** [comment]
@ohaiibuzzle 
I have cherry-picked the commit on UI improvements.
https://github.com/PlayCover/PlayCover/commit/1ea76d57cc6d33bc254cb6711ef982cb7683c520
Since I dropped the requirement of `ldid`, would you like to rebase the PR?

**Comment by ohaiibuzzle** [comment]
> @ohaiibuzzle I have cherry-picked the commit on UI improvements. [1ea76d5](https://github.com/PlayCover/PlayCover/commit/1ea76d57cc6d33bc254cb6711ef982cb7683c520) Since I dropped the requirement of `ldid`, would you like to rebase the PR?

Sure. I will close this PR (for now) and move it over to `develop` as well to avoid chaos

**Comment by ohaiibuzzle** [comment]
> @ohaiibuzzle I have cherry-picked the commit on UI improvements. [1ea76d5](https://github.com/PlayCover/PlayCover/commit/1ea76d57cc6d33bc254cb6711ef982cb7683c520) Since I dropped the requirement of `ldid`, would you like to rebase the PR?

Sure. Will be closing this PR (for now) and reopen it again after rebasing to avoid chaos

**Pull request closed without merging**
