### PR TITLE
Low Power Mode Alert

### PR DESCRIPTION
**Pull request by IsaacMarovitz**

### CODE REVIEW

**Comment by Depal1** [comment]
If this is to be done, it should only show for specific models since always plugged models don’t have a low power mode.

**Comment by Depal1** [comment]
At present, I don’t know how would it behave on the aforementioned Macs.

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment]
> At present, I don’t know how would it behave on the aforementioned Macs.

Would it just open normally if there is no low power mode support?

**Comment by IsaacMarovitz** [comment]
> At present, I don’t know how would it behave on the aforementioned Macs.

For Macs that don't have a Low Power Mode, I imagine the bool is just always set to false.

**Comment by KhoraLee** [comment]
> At present, I don’t know how would it behave on the aforementioned Macs.

It's old and iOS documentation but it is still linked in latest apple's developer documentation page. So it should be applied to mac too.
https://developer.apple.com/library/archive/documentation/Performance/Conceptual/EnergyGuide-iOS/LowPowerMode.html#//apple_ref/doc/uid/TP40015243-CH31
```
If the device’s power state is unknown or if the device doesn’t support Low Power Mode, then this property always has a value of NO.
```

**Review by Depal1 — APPROVED** [review]

**Pull request merged**
