### PR TITLE
General app settings tab

### PR DESCRIPTION
**Pull request by zanderp25**
I, and a few others, thought it would be nicer if the tabs with only a few items would be merged into a single "general" tab.
There are only a few changes needed with other localizations.

### CODE REVIEW

**Comment by zanderp25** [comment]
ah yes, the error suppressor is erroring

**Comment by zanderp25** [comment]
whoops did i accidentally commit my project file

**Comment by ZhichGaming** [comment]
Could you attach some screenshots?

**Comment by zanderp25** [comment]
Here's a screenshot
screenshot of general tab

**Comment by Depal1** [comment]
This was discussed recently, but was rejected because the keymapping and jailbreak tabs will accommodate more settings in the short term, such as entitlement customization for the latter.

As for `import keymapping` and `export keymapping`, they are not really settings.

**Comment by zanderp25** [comment]
> As for `import keymapping` and `export keymapping`, they are not really settings.

I forgot to mention that this was removed

**Pull request closed without merging**
