### PR TITLE
Removed a few things I forgot

### PR DESCRIPTION
**Pull request by zanderp25**
- removed some old color references
- changed the references to accentColor
- changed reset button style to look better
- fixed unreadable text
- removed Herobri- i mean unused "happy cat" icon

### CODE REVIEW

**Comment by zanderp25** [comment]
This PR has conflicts with #77, so i will rebase when that is approved

**Comment by Depal1** [comment]
#77 has been merged.

**Comment by zanderp25** [comment]
Alright, I have resolved the conflicts. It should be ready to merge now.

**Comment by zanderp25** [comment]
okay i have merged again @Depal1

**Review by Depal1 — APPROVED** [review]

**Comment by sheilalarmour** [comment]
It’s merged!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Pull request merged**
