### PR TITLE
Fixed comments in Localizable.strings

### PR DESCRIPTION
**Pull request by zanderp25**
I deleted the empty comments in the localization files and transferred the variable comments to all of the files. (those `/* @.f */` comments were for the variables, right?)

### CODE REVIEW

**Comment by zanderp25** [comment]
@IsaacMarovitz This PR has nothing to do with Weblate being down

**Comment by amirsaam** [comment]
Aren't those comments auto generated by Weblate in order to explain what is the usage of the strings in Weblate?

**Comment by zanderp25** [comment]
> Aren't those comments auto generated by Weblate in order to explain what is the usage of the strings in Weblate?

I don't think so, because it isn't doing it to the newer ones, and it's in some files more than others

**Comment by IsaacMarovitz** [comment]
These comments are added automatically by Weblate and have no effect on the functionality of the locales.

**Pull request closed without merging**
