### PR TITLE
feat: New App Signing configuration experience.

### PR DESCRIPTION
**Pull request by ohaiibuzzle**
This commit brings a new, guided approach for configuring app signing (which make login in apps like Genshin works)

The "wizard" guides the user through disabling SIP and disabling AMFI in a more visual manner.

Here is what it looks like:
Menu accessible via PlayCover > Configure Signing:
image

AMFI:
out

Signing ready:
image

### CODE REVIEW

**Comment by ZhichGaming** [comment]
Can you insert a button that links to the docs? Do the question marks point to their instructions as to how to set them?

**Comment by ohaiibuzzle** [comment]
> Can you insert a button that links to the docs? Do the question marks point to their instructions as to how to set them?

Those buttons provides information as to why we are disabling those macOS features when you hover over them
Docs, we have one on the Help menu, do you think we need it here as well?

**Comment by amirsaam** [comment]
I think this gives a the user a feeling that he/she needs to do it once. more details i think is required under title.
like "you need to do this process everytime you want to login into a new account" or something like this.

**Comment by ZhichGaming** [comment]
> > Can you insert a button that links to the docs? Do the question marks point to their instructions as to how to set them?
> 
> Those buttons provides information as to why we are disabling those macOS features when you hover over them Docs, we have one on the Help menu, do you think we need it here as well?

If It's only in the help menu, yes you should add a button linking to the docs maybe called "How to disable SIP and NVRAM" since people definitely would not know how to disable SIP without a guide and i would say most users do not know that we need to paste the nvram command in terminal.

**Comment by ZhichGaming** [comment]
> I think this gives a the user a feeling that he/she needs to do it once. more details i think is required under title. like "you need to do this process everytime you want to login into a new account" or something like this.

That is too Genshin specific, that pop up applies for a lot of apps.

**Comment by amirsaam** [comment]
> > I think this gives a the user a feeling that he/she needs to do it once. more details i think is required under title. like "you need to do this process everytime you want to login into a new account" or something like this.
> 
> That is too Genshin specific, that pop up applies for a lot of apps.

So, you don't have to disable sip everytime you want to login into a new account for a different app?

**Comment by ZhichGaming** [comment]
I mean for some apps, you need SIP disabled the whole time not just for logging in.

**Comment by amirsaam** [comment]
So there could simply be a note like: "not every app let's you stay logged in after enabling sip again" or something like this

**Comment by ohaiibuzzle** [comment]
I mean we can put up an abomination to modern design, ala. a wall of text, like so
image
if you are so worried about that

**Comment by amirsaam** [comment]
Lemme clarify, PlayCover dictionary is completely confusing. Words like PlayBook and PlayMap that currently are under use are not familiar to any user. I just saying we need to clarify not with a wall of words but with a couple of short notes.

Two note are necessary in my opinion that user should know:
- Some apps may be logged out after enabling SIP afterwards.
- If user wants to login into a new account, disabling SIP again is required.

**Review by Depal1 — APPROVED** [review]

**Pull request merged**
