### PR TITLE
Fix Settings render issues

### PR DESCRIPTION
**Pull request by Catta1997**
Start working on fix render issue of Settings UI where the toggle not update (state change but not graphically) 

- [x] KeyMapView
- [x] GraphicView
- [x] BypassView
- [x] MiscView
- [x] Check if ALL toggle are saved correctly

### CODE REVIEW

**Comment by Catta1997** [comment]
https://github.com/PlayCover/PlayCover/assets/34333654/b516a846-a77d-40e3-a70a-2e402623fbdb

**Comment by Catta1997** [comment]
Should be all, not totally sure if all settings is saved correctly. I checked MetalHUD and DiscordRP and both are correct

**Comment by mitchellmebane** [comment]
I built this branch and all the controls I tested work properly.

Clicking the "Fix window display issues" checkbox on the Graphics tab doesn't enable the dropdown next to it, but I've never used that, so I don't know how it's supposed to work. I can't seem to enable that dropdown in the old nightly 636, either.

**Comment by mitchellmebane** [comment]
After looking through the code, I see that the dropdown only gets enabled when "Fix window display issues" is checked _and_ "Resolution" is set to "App Default".  It's working properly in this branch.  👍

**Comment by TheMoonThatRises** [comment]
I think we should wait for an update from Apple, as this is most likely a bug and not intended behaviour. This does not occur on previous versions.

**Comment by Catta1997** [comment]
> I think we should wait for an update from Apple, as this is most likely a bug and not intended behaviour. This does not occur on previous versions.

oh ok, btw this is a thing in other part of the project ([Settings/InstallSettings.swift](https://github.com/PlayCover/PlayCover/blob/a14960e031fb703ca0e07a1d376a52623db5e0f6/PlayCover/Views/Settings/InstallSettings.swift#L13), [PlayCover/Views/Settings/UpdateSettings.swift](https://github.com/PlayCover/PlayCover/blob/a14960e031fb703ca0e07a1d376a52623db5e0f6/PlayCover/Views/Settings/UpdateSettings.swift#L13) and [PlayCover/Views/Settings/UninstallSettings.swift](https://github.com/PlayCover/PlayCover/blob/a14960e031fb703ca0e07a1d376a52623db5e0f6/PlayCover/Views/Settings/UninstallSettings.swift#L13)).

**Comment by mitchellmebane** [comment]
I may be way off base here, but is the issue the multi-level object nesting?  E.g., in the `AppSettingsView` tab views, [the views are binding to an instance of `AppSettings`](https://github.com/PlayCover/PlayCover/blob/3.0.0/PlayCover/Views/AppSettingsView.swift#L188), but [the controls are using an attribute of the nested `AppSettingsData`](https://github.com/PlayCover/PlayCover/blob/3.0.0/PlayCover/Views/AppSettingsView.swift#L217).

> ```swift
> Picker("", selection: $settings.settings.iosDeviceModel)
> ```

All the docs and examples of SwiftUI data binding I've seen either use a directly published property, or use a property of a published class. I haven't seen anything which uses a property in a struct nested in a published class.

**Comment by TheMoonThatRises** [comment]
> I may be way off base here, but is the issue the multi-level object nesting? E.g., in the `AppSettingsView` tab views, [the views are binding to an instance of `AppSettings`](https://github.com/PlayCover/PlayCover/blob/3.0.0/PlayCover/Views/AppSettingsView.swift#L188), but [the controls are using an attribute of the nested `AppSettingsData`](https://github.com/PlayCover/PlayCover/blob/3.0.0/PlayCover/Views/AppSettingsView.swift#L217).
> 
> > ```swift
> > Picker("", selection: $settings.settings.iosDeviceModel)
> > ```
> 
> All the docs and examples of SwiftUI data binding I've seen either use a directly published property, or use a property of a published class. I haven't seen anything which uses a property in a struct nested in a published class.

I believe that this is the issue. @Catta1997 if you want to try fixing it by removing the nesting of classes and structures, do try. If not, I can merge this as a temporary fix.

**Comment by Catta1997** [comment]
Ok, I will try

**Comment by Catta1997** [comment]
But since I don know a lot SwiftUI I think you can merge this temporary fix 'cause I don't know if I will be able to fix it in the other way

**Review by TheMoonThatRises — APPROVED** [review]

**Pull request merged**
